
export default [

    'EVENT_ADD_TASK',
    'EVENT_EDIT_TASK',
    'EVENT_REMOVE_TASK',
    'EVENTS_ADD_TASK',
    'EVENTS_SEARCH_TASK',
    'USERS_ADD_TASK',
    'USER_ADD_TASK',
    'USER_REGISTER_TASK',
    'USER_LOGIN_TASK',
    'USER_LOGOUT_TASK',
    'USER_REMOVE_TASK',
    'USER_PASSWORD_CHANGE_TASK',
    'TYPES_ADD_TASK',
    'CATEGORIES_ADD_TASK',
    'SUBCATEGORIES_ADD_TASK',

    'DATE_ADD',

    'EVENT_ADD',
    'EVENT_EDIT',
    'EVENT_REMOVE',

    'EVENTS_ADD',

    "TOGGLE_POPUP_NAV_MAIN",
    "TOGGLE_POPUP_NAV_USER",
    "TOGGLE_POPUP_EVENT_ADD",
    "TOGGLE_POPUP_EVENT_EDIT",
    "TOGGLE_POPUP_EVENT_REMOVE",
    "TOGGLE_POPUP_USER_REGISTER",
    "TOGGLE_POPUP_USER_LOGIN",
    "TOGGLE_POPUP_DATE_PICKER",

    'USER_ADD',

    'USERS_ADD',

    'TYPES_ADD',
    'CATEGORIES_ADD',
    'SUBCATEGORIES_ADD',

].reduce((acc, type) => {
    acc[type] = type;
    return acc;
}, {});
