
export default {

    // for middleware (like saga)
    EVENT_ADD_TASK: 'EVENT_ADD_TASK',
    EVENT_EDIT_TASK: 'EVENT_EDIT_TASK',
    EVENT_REMOVE_TASK: 'EVENT_REMOVE_TASK',

    // for store
    EVENT_ADD: 'EVENT_ADD',
    EVENT_EDIT: 'EVENT_EDIT',
    EVENT_REMOVE: 'EVENT_REMOVE',

    // for popups
    TOGGLE_POPUP_NAV_MAIN: "TOGGLE_POPUP_NAV_MAIN",
    TOGGLE_POPUP_NAV_MAIN: "TOGGLE_POPUP_NAV_MAIN",
    TOGGLE_POPUP_NAV_USER: "TOGGLE_POPUP_NAV_USER",
    TOGGLE_POPUP_EVENT_ADD: "TOGGLE_POPUP_EVENT_ADD",
    TOGGLE_POPUP_EVENT_EDIT: "TOGGLE_POPUP_EVENT_EDIT",
    TOGGLE_POPUP_EVENT_DELETE: "TOGGLE_POPUP_EVENT_DELETE",
    TOGGLE_POPUP_USER_REGISTER: "TOGGLE_POPUP_USER_REGISTER",
    TOGGLE_POPUP_USER_LOGIN: "TOGGLE_POPUP_USER_LOGIN",
    TOGGLE_POPUP_DATE_PICKER: "TOGGLE_POPUP_DATE_PICKER",

}